requires = ["tox>=4"]
env_list = ["benchmarks"]

[env_run_base]
description = "run benchmarks"
commands = [["pytest", { replace = "posargs", default=["benchmarks/"], extend = true }, "--benchmark-save-data", "--benchmark-json=bench-results.json"]]
